import Providers from "@/providers";
import { TranslationPropType } from "@/_types/i18n.types";
import { getMessages } from "next-intl/server";

import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";

// const geistSans = Geist({S
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
  params: TranslationPropType;
};

export default async function RootLayout({
  children,
  params
}: RootLayoutProps) {
  const { locale } = await params
  const messages = await getMessages({ locale });
  const session = await getServerSession(authOptions);
  return (
    <html lang={locale} suppressHydrationWarning>
    <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      suppressHydrationWarning={true}
    >
    <Providers locale={locale} messages={messages} session={session}>
      {children}
    </Providers>
    </body>
    </html>
  )
}
