import Providers from "@/providers";
import { TranslationPropType } from "@/_types/i18n.types";
import { getMessages } from "next-intl/server";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
  params: TranslationPropType;
};

export default async function RootLayout({
  children,
  params
}: RootLayoutProps) {
  const { locale } = await params
  const messages = await getMessages({ locale });
  return (
    <html lang={locale}>
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      suppressHydrationWarning={true}
    >
    <Providers locale={locale} messages={messages}>
      {children}
    </Providers>
    </body>
    </html>
  )
}
