import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import PageError from './error';
import React from "react";

// import { AppLayout, BackButtonLayout, FooterLayout, LanguageSelectorLayout } from "@/_layouts";

// import type { Metadata } from "next";
//
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ErrorBoundary errorComponent={PageError}>
      {children}
    </ErrorBoundary>
  );
}
